name: mynoteactions
on: 
  schedule:
    - cron: '5 9-14 * * 0,1,3,4,5,6'
  workflow_dispatch:
jobs:
  insert-todays-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: get baseball
        env: 
          GOOGLE_CHAT_URL: ${{ secrets.GOOGLE_CHAT_URL }}
          TZ: "Asia/Tokyo"
        run: NODE_OPTIONS='--experimental-fetch' ./node_modules/.bin/ts-node src/actions.ts